# Generated by Django 5.1.2 on 2024-11-05 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('style', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='style',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('height', models.CharField(max_length=20)),
                ('setting', models.CharField(max_length=20)),
                ('weather', models.CharField(max_length=20)),
                ('type', models.CharField(max_length=20)),
            ],
        ),
        migrations.DeleteModel(
            name='Test',
        ),
    ]
