# Generated by Django 5.1.2 on 2024-11-05 02:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('style', '0003_clothstyle'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='style',
            new_name='personstyle',
        ),
    ]
